# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'lesson15' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lesson15
  pod 'SnapKit', '~> 5.0.1'
  pod 'Alamofire', '~> 5.5'

end
